### ISSUE TITLE
Merge HIFLD data into HCRIS data

### ISSUE THREAD

**Issue by lossyrob** [daveluo/covid19-healthsystemcapacity#25]
See issue comment https://github.com/daveluo/covid19-healthsystemcapacity/issues/14#issuecomment-599885877

This data should be merged into `usa_hospital_beds_hcris2018_cleaned3.geojson` in the data folder. The 'BEDS' field should be renamed to 'Total Licensed Beds'. Unclear what other columns should be carried over - perhaps an object inside the feature properties that just has everything, with a property name `hifld`?

Since there are lat lng coordinates in the HIFLD data, we can do a spatial join on buffered points to match the datasets.

**Comment by daveluo** [comment]
I would carry over all of the nonredundant columns from HIFLD. This dataset seems to be designed for purpose-made to facilitate emergency/crisis management, i.e. with columns like HELIPAD, STATUS, TRAUMA, TYPE, OWNER

For example, STATUS == CLOSED facilities we can use to flag facilities that can be re-opened to add capacity.

**Comment by aaronxsu** [comment]
From https://github.com/daveluo/covid19-healthsystemcapacity/issues/14#issuecomment-599571862, these are the target statistics we're aiming to derive with this data:

- total licensed non-ICU beds & % of these staffed
- total licensed ICU beds & % of these staffed
- total number of vents & % of these available

**Comment by daveluo** [comment]
Note that we're mainly been focused on acute care capacity/bed supply for adults (these hospital types are often labeled as "Acute Care Hospital" or "Critical Access") right now but there are many other facility types in these datasets (like Peds and Womens' hospitals, nursing facilities, long term rehab). I'm guessing the processing and data merge is mostly the same amoubt of work whether we keep all facility types in or not? If so, preference is to keep every facility in the combined dataset and just not expose it to view for now

**Comment by daveluo** [comment]
Heads-up re: the HFILD data and some potentially missing data points (which we can quickly crosscheck against our HCRIS data by state or county):

thanks to https://forums.fast.ai/t/help-with-algorithm-for-covid19-relative-risk/65328/15:
>About HIFLD, we are only showing in NY 1/10 of the beds they actually have, so there may be bad data, or I may have done something in preprocessing. I’m going to take a closer look soon but just make sure your data for NY State is checked/working.

**Comment by daveluo** [comment]
See attached for the reference documentation about our HCRIS reported data (which is for all Hospital facilities as defined here and who submit that "2010" form: https://www.cms.gov/Research-Statistics-Data-and-Systems/Downloadable-Public-Use-Files/Cost-Reports/Hospital-2010-form)

from "HOSPITAL2010-DOCUMENATION.ZIP" in the above link
[HOSP2010_README.txt](https://github.com/daveluo/covid19-healthsystemcapacity/files/4344827/HOSP2010_README.txt)
